apiVersion: apps/v1
kind: Deployment
metadata:
   name: reactdeploy
spec:
   replicas: 2
   selector:
    matchLabels:
      app: reactdeploy
   template:
      metadata:
        labels:
          app: reactdeploy
      spec:
        containers:
        - name: hello-pod
          image: shirishgund/reactapp1:latest
          ports:
          - containerPort: 3000

