apiVersion: apps/v1
kind: Deployment
metadata:
   name: React_deploy
spec:
   replicas: 2
   selector:
    matchLabels:
      app: React_deploy
   template:
      metadata:
        labels:
          app: React_deploy
      spec:
        containers:
        - name: hello-pod
          image: shirishgund/reactapp1:latest
          ports:
          - containerPort: 8070

