apiVersion: v1
kind: Service 
metadata:
   name: hello-svc
   labels:
        app: React_deploy
spec:
   type: NodePort
   ports:
   - port: 8070
     nodePort: 3200   (bound 8080 to 300001 port)
     protocol: TCP
   Selector:
     app: React_deploy
